name: Create prerelease

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  create-prerelease:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - id: release-drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: configurations/release-drafter.yml
          disable-autolabeler: true
          publish: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Verify release
        if: steps.release-drafter.outputs.id == ''
        run: exit 1
