name: Deploy

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  deploy:
    needs: []
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  update-latest-release:
    needs:
      - deploy
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG_NAME_PATTERN: '^v'
    steps:
      - uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags --force

      - name: Find out the release tag with the commit hash
        run: >
          git tag --points-at="${GITHUB_SHA}" --sort=-refname |
          grep -E "${RELEASE_TAG_NAME_PATTERN}" |
          head -n 1 |
          echo "RELEASE_TAG=$(cat)" >> $GITHUB_ENV

      - name: Mark the release as "Latest"
        run: gh release edit "${RELEASE_TAG}" --prerelease=false --latest
        env:
          GH_TOKEN: ${{ github.token }}
