name: Update latest release

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  deployment_status

defaults:
  run:
    shell: bash

env:
  RELEASE_TAG_NAME_PATTERN: '^v'

jobs:
  update-latest-release:
    if: >
      github.event.deployment_status.environment == 'production' &&
      github.event.deployment_status.state == 'success'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: git fetch --tags --force

      - name: Find out the release tag with the commit hash
        run: >
          git tag --points-at="${GITHUB_SHA}" --sort=-refname |
          grep -E "${RELEASE_TAG_NAME_PATTERN}" |
          head -n 1 |
          echo "RELEASE_TAG=$(cat)" >> $GITHUB_ENV

      - name: Mark the release as "Latest"
        run: gh release edit "${RELEASE_TAG}" --prerelease=false --latest
        env:
          GH_TOKEN: ${{ github.token }}
